Map <String, String> ar={
  'Email': 'البريد الالكتروني',
  'Password': 'كلمة المرور',
  'Login':'تسجيل الدخول',
  'Welcome Back':'أهلاً مجدداً',
  'please sign in to your account':'الرجاء تسجيل الدخول لحسابك',
  'Don\'t have an account?':'ليس لديك حساب ؟',
  'Sign up':'تسجيل حساب',
  'Create New Account':'انشاء حساب جديد',
  'please fill in the form to continue':'الرجاء تعبئة معلوماتك للمتابعة',
  'Name':'الاسم',
  'Confirm Password':'تأكيد كلمة المرور',
  'Register':'تسجيل',
  'Already have an account?':'لديك حساب سابق ؟ ',
  'Sign in':'تسجيل الدخول',
  'Name is Empty ! ':'! الاسم فارغ',
  'Email is empty ! ':'! البريد الالكتروني فارغ',
  'Password Is Empty ! ':'! كلمة المرور فارغة',
  'Confirm Password Is Empty ! ':'! تأكيد كلمة المرور فارغ',
  'Summary':'الملخص',
  'Tasks\nDone':'مهام\n منتهية',
  'My Projects':'مشاريعي',
  'Sample Project':'مشروع معين',
  "Pending":"معلق",
  'Add new sprint':'اضافة قائمة مهام جديدة',
  'Home':'الصفحة الرئيسية',
  'Sample Projects':'مشاريع معينة',
  'Settings':'الاعدادات',
  'Notifications':'الاشعارات',
  'Add Project':'اضافة مشروع',
  'WorkSpaces':'مساحة العمل',
  'Todo Tasks':'مهام لفعلها',
  'header':'عنوان',
  'Keep me sign in':'أبقني متصلا',
  'Please Enter at least 8 Characters !':'! الرجاء ادخال 8 محارف على الأقل',
  'Not equal to the password ! ':'! لا يطابق كلمة المرور',
  'Phone number is empty !':'! رقم الهاتف فارغ',
  'Phone ':'رقم الهاتف',
  'Build Your Task':'قم ببناء مهمتك',
  'Approved':'الموافقة',
  'Due Date':'اضافة وقت',
  'Fields':'الحقول',
  'Priority':'الأولوية',
  'Low':'منخفضة',
  'Medium':'متوسطة',
  'High':'مرتفعة',
  'Description':'التوصيف',
  'Image':'الصورة',
  'Sub Task':'مهمة مرتبطة',
  'Sub Tasks':'مهام مرتبطة',
  'Add More Details to this Task':'اضافة المزيد من التفاصيل على هذه المهمة',
  'Language':'اللغة',
  'Theme':'السمة',
  'Dark':'مظلم',
  'Pink':'زهري',
  'Purple':'بنفسجي',
  'Blue':'أزرق',
  'rate user ':'قيّم المستخدم ',
  'Please leave a star rating':'الرجاء التقييم بالنجوم',
  'Task Title':'عنوان المهمة ',
  "Statues":"الحالات",
  "Users":"المستخدمون",
  'Add':'اضافة',
  'Add Task':'اضافة مهمة',
  'Task Name':'اسم المهمة',
  'My Tasks':'مهامي',
  'Task Details : ':'معلومات المهمة:',
  'there is no description':'لا يوجد توصيف',
  'Task Deadline : ':'موعد التسليم :',
  'Cancel':'الغاء',
  'Are you sure you ant to delete this task ? ':'هل أنت متأكد أنك تريد مسح هذه المهمة ؟ ',
  'No':'لا',
  'Yes':'نعم',
  'Delete Task':'مسح المهمة',
  'Title':'عنوان',
  'Add Title to this task':'أضف عنوان لهذه المهمة',
  'Select User to Assign':'اختر مستخدم لاسناده',
  'Add Sub Task':'أضف مهمة فرعية',
  'Loading...':'يحمل...',
  'are you sure you want to log out ? ':'هل أنت متأكد أنك تريد تسجيل الخروج ؟ ',
  'Only view my tasks':'فقط أظهر مهامي',
  'Days Left :':'الأيام المتبقية :',
  'Activate':'تفعيل',
  "Personal Task":"مهمة شخصية",
  "Personal Tasks":"مهام شخصية",
' of ': ' من ',
  'Completed Tasks :':' المهام المنتهية :',
  'This Project Progress to Others :':'تقدم هذا المشروع نسبة لباقي المشاريع :',
  "Agenda":"جدول الأعمال",
  'tap on the icon to unpin the task':'اضفط على الأيقونة لازالة جدولة المهمة',
  'Project Title':'عنوان المشروع',
  'No Internet Connection':'لا يوجد اتصال بالانترنت',

  'About':'حول',
  'Log out':'تسجيل الخروج',















};
