Map <String, String> en={
  'Email': 'Email',
  'Password': 'Password',
  'Login':'Login',
  'Welcome Back':'Welcome Back',
  'please sign in to your account':'please sign in to your account',
  'Don\'t have an account?':'Don\'t have an account?',
  'Sign up':'Sign up',
  'Create New Account':'Create New Account',
  'please fill in the form to continue':'please fill in the form to continue',
  'Name':'Name',
  'Confirm Password':'Confirm Password',
  'Register':'Register',
  'Already have an account?':'Already have an account?',
  'Sign in':'Sign in',
  'Name is Empty ! ':'Name is Empty ! ',
  'Email is empty ! ':'Email is empty ! ',
  'Password Is Empty ! ':'Password Is Empty ! ',
  'Confirm Password Is Empty ! ':'Confirm Password Is Empty ! ',
  'Summary':'Summary',
  'Tasks\nDone':'Tasks\nDone',
  'My Projects':'My Projects',
  'Sample Project':'Sample Project',
  "Pending":"Pending",
  'Add new sprint':'Add new sprint',
  'Home':'Home',
  'Sample Projects':'Sample Projects',
  'Settings':'Settings',
  'Notifications':'Notifications',
  'Add Project':'Add Project',
  'WorkSpaces':'WorkSpaces',
  'Todo Tasks':'Todo Tasks',
  'header':'header',
  'Keep me sign in':'Keep me sign in',
  'Please Enter at least 8 Characters !':'Please Enter at least 8 Characters !',
  'Not equal to the password ! ':'Not equal to the password ! ',
  'Phone number is empty !':'Phone number is empty !',
  'Phone ':'Phone ',
  'Build Your Task':'Build Your Task',
  'Approved':'Approved',
  'Due Date':'Due Date',
  'Fields':'Fields',
  'Priority':'Priority',
  'Low':'Low',
  'Medium':'Medium',
  'High':'High',
  'Description':'Description',
  'Image':'Image',
  'Sub Task':'Sub Task',
  'Sub Tasks':'Sub Tasks',
  'Add More Details to this Task':'Add More Details to this Task',
  'Language':'Language',
  'Theme':'Theme',
  'Dark':'Dark',
  'Pink':'Pink',
  'Purple':'Purple',
  'Blue':'Blue',
  'rate user ':'rate user ',
  'Please leave a star rating':'Please leave a star rating',
  'Task Title':'Task Title',
  "Statues":"Statues",
  "Users":"Users",
  'Add':'Add',
  'Add Task':'Add Task',
  'Task Name':'Task Name',
  'My Tasks':'My Tasks',
  'Task Details : ':'Task Details : ',
  'there is no description':'there is no description',
  'Task Deadline : ':'Task Deadline : ',
  'Cancel':'Cancel',
  'Are you sure you ant to delete this task ? ':'Are you sure you ant to delete this task ? ',
  'No':'No',
  'Yes':'Yes',
  'Delete Task':'Delete Task',
  'Title':'Title',
  'Add Title to this task':'Add Title to this task',
  'Select User to Assign':'Select User to Assign',
  'Add Sub Task':'Add Sub Task',
  'Loading...':'Loading...',
  'are you sure you want to log out ? ':'are you sure you want to log out ? ',
  'Only view my tasks':'Only view my tasks',
  'Days left :':'Days left :',
  'Activate':'Activate',
  "Personal Task":"Personal Task",
  "Personal Tasks":"Personal Tasks",
  ' of ': ' of ',
  'Completed Tasks :':'Completed Tasks :',
  'This Project Progress to Others :':'This Project Progress to Others :',
  "Agenda":"Agenda",
  'tap on the icon to unpin the task':'tap on the icon to unpin the task',
  'Project Title':'Project Title',
  'No Internet Connection':'No Internet Connection',




};
