Map <String, String> en={
  'Email': 'Email',
  'Password': 'Password',
  'Login':'Login',
  'Welcome Back':'Welcome Back',
  'please sign in to your account':'please sign in to your account',
  'Don\'t have an account?':'Don\'t have an account?',
  'Sign up':'Sign up',
  'Create New Account':'Create New Account',
  'please fill in the form to continue':'please fill in the form to continue',
  'Name':'Name',
  'Confirm Password':'Confirm Password',
  'Register':'Register',
  'Already have an account?':'Already have an account?',
  'Sign in':'Sign in',
  'Name is Empty ! ':'Name is Empty ! ',
  'Email is empty ! ':'Email is empty ! ',
  'Password Is Empty ! ':'Password Is Empty ! ',
  'Confirm Password Is Empty ! ':'Confirm Password Is Empty ! ',
  'Summary':'Summary',
  'Tasks\nDone':'Tasks\nDone',
  'My Projects':'My Projects',
  'Sample Project':'Sample Project',
  "Pending":"Pending",
  'Add new sprint':'Add new sprint',
  'Home':'Home',
  'Sample Projects':'Sample Projects',
  'Settings':'Settings',
  'Notifications':'Notifications',
  'Add Project':'Add Project',
  'WorkSpaces':'WorkSpaces',
  'Todo Tasks':'Todo Tasks',
  'header':'header',
  'Keep me sign in':'Keep me sign in',
};
